FROM java:8
VOLUME /tmp
ADD target/solution-0.0.1-SNAPSHOT.jar reports-service-app.jar
EXPOSE 8080
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /reports-service-app.jar" ]
